apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripilot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripilot-postgres
  template:
    metadata:
      labels:
        app: tripilot-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: tripilot-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tripilot-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "tripilot_db"]
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tripilot-postgres
spec:
  selector:
    app: tripilot-postgres
  ports:
    - port: 5432
      targetPort: 5432
