apiVersion: 1

datasources:
  - name: TripPilot-Postgres
    uid: tripilot-postgres
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
