import duckdb

# Connect to the DuckDB database generated by dlt
conn = duckdb.connect("logfire_traces_pipeline.duckdb")

# Query table count in the 'agent_traces' schema
query = """
SELECT COUNT(*) 
FROM information_schema.tables 
WHERE table_schema = 'agent_traces';
"""

table_count = conn.execute(query).fetchone()[0]
print(f"Total tables created in 'agent_traces' schema: {table_count}")
