apiVersion: v1
kind: ConfigMap
metadata:
  name: complaintradar-config
  namespace: default
data:
  USE_DOCKER: "true"
  ELASTICSEARCH_URL: "http://complaintradar-elasticsearch:9200"
  POSTGRES_HOST: "complaintradar-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "complaintradar_db"
  POSTGRES_USER: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: complaintradar-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  GROQ_API_KEY: ""
