apiVersion: apps/v1
kind: Deployment
metadata:
  name: findocs-grafana
  namespace: default
  labels:
    app: findocs-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: findocs-grafana
  template:
    metadata:
      labels:
        app: findocs-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.2.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: findocs-secret
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: findocs-grafana
  namespace: default
spec:
  selector:
    app: findocs-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer # Or NodePort for local Minikube/Kind testing
