apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: findocs_db
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
